error: an entrypoint that calls `App::run()` does not return `AppExit`
  --> tests/ui/main_return_without_appexit/bug_132.rs:18:16
   |
14 | fn main() {
   |          - help: try: `-> AppExit`
...
18 |     App::new().run();
   |                ^^^^^
   |
   = note: `App::run()` returns `AppExit`, which can be used to determine whether the app exited successfully or not
note: the lint level is defined here
  --> tests/ui/main_return_without_appexit/bug_132.rs:10:9
   |
10 | #![deny(bevy::main_return_without_appexit)]
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 1 previous error

