error: an entrypoint that calls `App::run()` does not return `AppExit`
  --> tests/ui/main_return_without_appexit/bug_94.rs:13:5
   |
9  | fn main() {
   |          - help: try: `-> AppExit`
...
13 |     App::run(&mut app);
   |     ^^^^^^^^^^^^^^^^^^
   |
   = note: `App::run()` returns `AppExit`, which can be used to determine whether the app exited successfully or not
note: the lint level is defined here
  --> tests/ui/main_return_without_appexit/bug_94.rs:5:9
   |
5  | #![deny(bevy::main_return_without_appexit)]
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 1 previous error

