error: an entrypoint that calls `App::run()` does not return `AppExit`
  --> tests/ui/main_return_without_appexit/main.rs:15:16
   |
9  | fn main() {
   |          - help: try: `-> AppExit`
...
15 |     App::new().run();
   |                ^^^^^
   |
   = note: `App::run()` returns `AppExit`, which can be used to determine whether the app exited successfully or not
note: the lint level is defined here
  --> tests/ui/main_return_without_appexit/main.rs:5:9
   |
5  | #![deny(bevy::main_return_without_appexit)]
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: an entrypoint that calls `App::run()` does not return `AppExit`
  --> tests/ui/main_return_without_appexit/main.rs:18:5
   |
9  | fn main() {
   |          - help: try: `-> AppExit`
...
18 |     App::run(&mut app);
   |     ^^^^^^^^^^^^^^^^^^
   |
   = note: `App::run()` returns `AppExit`, which can be used to determine whether the app exited successfully or not

error: aborting due to 2 previous errors

