error: called `App::run()` without handling the returned `AppExit`
  --> tests/ui/unused_appexit/entry_fn.rs:10:16
   |
10 |     App::new().run();
   |                ^^^^^
   |
   = note: `App::run()` returns `AppExit`, which is used to determine whether the app exited successfully or not
   = help: `AppExit` implements `Termination`, so it can be returned directly from `fn main()`
note: the lint level is defined here
  --> tests/ui/unused_appexit/entry_fn.rs:4:9
   |
4  | #![deny(bevy::unused_appexit)]
   |         ^^^^^^^^^^^^^^^^^^^^
help: return the result of `App::run()`
   |
10 |     return App::new().run();
   |     ~~~~~~~~~~~~~~~~~~~~~~~
help: set the return type of `fn main()`
   |
9  | fn main() -> AppExit {
   |           ++++++++++

error: aborting due to 1 previous error

