error: called `App::run()` without handling the returned `AppExit`
 --> tests/ui/unused_appexit/main.rs:9:16
  |
9 |     App::new().run();
  |                ^^^^^
  |
  = note: `App::run()` returns `AppExit`, which is used to determine whether the app exited successfully or not
  = help: `AppExit` implements `Termination`, so it can be returned directly from `fn main()`
note: the lint level is defined here
 --> tests/ui/unused_appexit/main.rs:3:9
  |
3 | #![deny(bevy::unused_appexit)]
  |         ^^^^^^^^^^^^^^^^^^^^
help: return the result of `App::run()`
  |
9 |     return App::new().run();
  |     ~~~~~~~~~~~~~~~~~~~~~~~
help: set the return type of `fn main()`
  |
7 | fn main() -> AppExit {
  |           ++++++++++

error: aborting due to 1 previous error

